# Generated by Django 3.2.10 on 2022-04-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billings',
            name='amount',
            field=models.IntegerField(default='', max_length=50),
        ),
    ]
