"""First migration

Revision ID: 02f92e74103f
Revises: ffa030453940
Create Date: 2022-04-20 23:18:16.542283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f92e74103f'
down_revision = 'ffa030453940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
