"""First migration

Revision ID: 3fae43387bd0
Revises: 50184012140d
Create Date: 2022-04-21 00:13:28.672141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fae43387bd0'
down_revision = '50184012140d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
