"""First migration

Revision ID: 50184012140d
Revises: 6215609f1b30
Create Date: 2022-04-20 23:59:54.685829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50184012140d'
down_revision = '6215609f1b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
