"""First migration

Revision ID: 6215609f1b30
Revises: 98be5a422867
Create Date: 2022-04-20 23:55:13.409802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6215609f1b30'
down_revision = '98be5a422867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
