"""First migration

Revision ID: 98be5a422867
Revises: 99ff1c6317f9
Create Date: 2022-04-20 23:50:52.606415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98be5a422867'
down_revision = '99ff1c6317f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
