"""First migration

Revision ID: 99ff1c6317f9
Revises: b26c4bdf468b
Create Date: 2022-04-20 23:33:13.479783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ff1c6317f9'
down_revision = 'b26c4bdf468b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
