"""First migration

Revision ID: b26c4bdf468b
Revises: 02f92e74103f
Create Date: 2022-04-20 23:28:00.618640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b26c4bdf468b'
down_revision = '02f92e74103f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
