"""First migration

Revision ID: ffa030453940
Revises: c882997373a0
Create Date: 2022-04-20 23:12:19.463696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa030453940'
down_revision = 'c882997373a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'amount')
    # ### end Alembic commands ###
